//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int listingID { get; set; }
        public int personID { get; set; }
        public int propertyID { get; set; }
        public Nullable<System.DateTime> listingStartTime { get; set; }
        public Nullable<System.DateTime> listingExpiryTime { get; set; }
        public Nullable<int> cleaningLevelID { get; set; }
        public string additionalInfo { get; set; }
        public int isLive { get; set; }
    
        public virtual CleaningLevel CleaningLevel { get; set; }
        public virtual Person Person { get; set; }
        public virtual Property Property { get; set; }
    }
}
