//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyInfo
    {
        public int propertyInfoID { get; set; }
        public int propertyID { get; set; }
        public Nullable<int> numBedrooms { get; set; }
        public Nullable<int> numBathrooms { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<double> priceLight { get; set; }
        public Nullable<double> priceMedium { get; set; }
        public Nullable<double> priceHeavy { get; set; }
        public string description { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
